# Generated by Django 6.1 on 2026-09-09 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_repair_experience_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic / Scholarship'), ('competition', 'Competition / Hackathon'), ('leadership', 'Leadership / Organizational'), ('honor', 'Honorary Mention')], default='competition', max_length=50)),
                ('date_awarded', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('bachelor', 'S1 / Bachelor Degree'), ('secondary_school', 'SMP/SMA / High School'), ('diploma', 'Diploma'), ('master', 'S2 / Master Degree')], default='bachelor', max_length=50)),
                ('field_of_study', models.CharField(default='Computer Science', max_length=255)),
                ('date_range', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
