# Generated by Django 6.1 on 2026-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'S1 / Bachelor Degree'), ('secondary_school', 'SMP/SMA / High School'), ('diploma', 'Diploma'), ('master', 'S2 / Master Degree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=255),
        ),
    ]
