# Generated by Django 6.1 on 2026-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic / Scholarship'), ('competition', 'Competition / Hackathon'), ('leadership', 'Leadership / Organizational'), ('honor', 'Honorary Mention')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_ongoing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
