# Generated by Django 6.1 on 2026-09-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_award_category_alter_experience_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'S1 / Bachelor Degree'), ('secondary_school', 'SMP / SMA / High School'), ('diploma', 'Diploma'), ('master', 'S2 / Master Degree')], max_length=50),
        ),
    ]
